### Get All Breeds
GET https://frontend-take-home-service.fetch.com/dogs/breeds
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM5MzI0OTk3LCJleHAiOjE3MzkzMjg1OTd9.s_TZf3jX_E2Me8AvkUN8QEmj-pE86q8xm-ZdcWq9w8Y;