### Get All Breeds
GET https://frontend-take-home-service.fetch.com/dogs/breeds
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5kZW9AZXhtYXBsZS5jb20iLCJpYXQiOjE3MzkwNDUzODYsImV4cCI6MTczOTA0ODk4Nn0.9k0Pywto2NM0hFLZl6i_D9TmmaE90_N-2eurEwVzqTk